# Generated by Django 4.2 on 2024-05-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_proyecto_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='num_celular',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
