# Generated by Django 4.2 on 2024-05-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_contacto_num_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='foto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='url_foto',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='url_foto',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
