# Generated by Django 4.2 on 2024-05-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_proyecto_foto_remove_servicio_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='url_foto',
            field=models.URLField(max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='url_foto',
            field=models.URLField(max_length=550, null=True),
        ),
    ]
