# Generated by Django 4.2 on 2024-05-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_proyecto_url_foto_alter_servicio_url_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='url_foto',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='url_foto',
            field=models.TextField(null=True),
        ),
    ]
