# Generated by Django 4.2 on 2024-05-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_proyecto_url_foto_alter_servicio_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='link_pdf',
            field=models.URLField(blank=True, max_length=390, null=True),
        ),
    ]
